# Generated by Django 4.1.10 on 2023-08-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='model',
            name='text_data',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='model',
            name='text_vectorized',
            field=models.CharField(max_length=255),
        ),
    ]
